# TODO Travis CI now supports only Ubuntu 12.04 and 14.04,
# which are TOO old for us. Wait for 'xenial' support or
# install Qt >= 5.3 and CMake >= 3.0 from some PPA
language: cpp
compiler:
  - gcc
  - clang
dist: xenial
addons:
  apt:
    packages:
      - python3-all
      - qt5-default
      - qtscript5-dev
      - libssl-dev
      - qttools5-dev
      - qttools5-dev-tools
      - qtmultimedia5-dev
      - libqt5svg5-dev
      - libqt5webkit5-dev
      - libsdl2-dev
      - libasound2
      - libxmu-dev
      - libxi-dev
      - freeglut3-dev
      - libasound2-dev
      - libjack-jackd2-dev
      - libxrandr-dev
      - libqt5xmlpatterns5-dev
      - libqt5xmlpatterns5
      - libqt5xmlpatterns5-private-dev
      - libqt5x11extras5-dev
script:
    - mkdir build
    - cd build
    - cmake -DUSE_QT=5 ..
    - make

